export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';


export const AVATAR_REQUEST = 'AVATAR_REQUEST';
export const AVATAR_SUCCESS = 'AVATAR_SUCCESS';
export const AVATAR_FAILURE = 'AVATAR_FAILURE';


export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const FORGOTPASSWORD_REQUEST = 'FORGOTPASSWORD_REQUEST';
export const FORGOTPASSWORD_SUCCESS = 'FORGOTPASSWORD_SUCCESS';
export const FORGOTPASSWORD_FAILURE = 'FORGOTPASSWORD_FAILURE';

export const CHNAGEPASSWORD_REQUEST = 'CHNAGEPASSWORD_REQUEST';
export const CHNAGEPASSWORD_SUCCESS = 'CHNAGEPASSWORD_SUCCESS';
export const CHNAGEPASSWORD_FAILURE = 'CHNAGEPASSWORD_FAILURE';


export const REGISTER_USERROLE_REQUEST = 'REGISTER_USERROLE_REQUEST';
export const REGISTER_USERROLE_SUCCESS = 'REGISTER_USERROLE_SUCCESS';
export const REGISTER_USERROLE_FAILURE = 'REGISTER_USERROLE_FAILURE';

export const COUNT_USERROLE_REQUEST = 'COUNT_USERROLE_REQUEST';
export const COUNT_USERROLE_SUCCESS = 'COUNT_USERROLE_SUCCESS';
export const COUNT_USERROLE_FAILURE = 'COUNT_USERROLE_FAILURE';

export const GETUSERROLE_REQUEST = 'GETUSERROLE_REQUEST';
export const GETUSERROLE_SUCCESS = 'GETUSERROLE_SUCCESS';
export const GETUSERROLE_FAILURE = 'GETUSERROLE_FAILURE';

export const DELETEUSERROLE_REQUEST = 'DELETEUSERROLE_REQUEST';
export const DELETEUSERROLE_SUCCESS = 'DELETEUSERROLE_SUCCESS';
export const DELETEUSERROLE_FAILURE = 'DELETEUSERROLE_FAILURE';

export const UPDATEUSERROLE_REQUEST = 'UPDATEUSERROLE_REQUEST';
export const UPDATEUSERROLE_SUCCESS = 'UPDATEUSERROLE_SUCCESS';
export const UPDATEUSERROLE_FAILURE = 'UPDATEUSERROLE_FAILURE';

export const SEARCHUSERROLE_REQUEST = 'SEARCHUSERROLE_REQUEST';
export const SEARCHUSERROLE_SUCCESS = 'SEARCHUSERROLE_SUCCESS';
export const SEARCHUSERROLE_FAILURE = 'SEARCHUSERROLE_FAILURE';

export const REGISTER_USERRIGHT_REQUEST = 'REGISTER_USERRIGHT_REQUEST';
export const REGISTER_USERRIGHT_SUCCESS = 'REGISTER_USERRIGHT_SUCCESS';
export const REGISTER_USERRIGHT_FAILURE = 'REGISTER_USERRIGHT_FAILURE';

export const COUNT_USERRIGHT_REQUEST = 'COUNT_USERRIGHT_REQUEST';
export const COUNT_USERRIGHT_SUCCESS = 'COUNT_USERRIGHT_SUCCESS';
export const COUNT_USERRIGHT_FAILURE = 'COUNT_USERRIGHT_FAILURE';

export const GETUSERRIGHT_REQUEST = 'GETUSERRIGHT_REQUEST';
export const GETUSERRIGHT_SUCCESS = 'GETUSERRIGHT_SUCCESS';
export const GETUSERRIGHT_FAILURE = 'GETUSERRIGHT_FAILURE';

export const DELETEUSERRIGHT_REQUEST = 'DELETEUSERRIGHT_REQUEST';
export const DELETEUSERRIGHT_SUCCESS = 'DELETEUSERRIGHT_SUCCESS';
export const DELETEUSERRIGHT_FAILURE = 'DELETEUSERRIGHT_FAILURE';

export const UPDATEUSERRIGHT_REQUEST = 'UPDATEUSERRIGHT_REQUEST';
export const UPDATEUSERRIGHT_SUCCESS = 'UPDATEUSERRIGHT_SUCCESS';
export const UPDATEUSERRIGHT_FAILURE = 'UPDATEUSERRIGHT_FAILURE';

export const SEARCHUSERRIGHT_REQUEST = 'SEARCHUSERRIGHT_REQUEST';
export const SEARCHUSERRIGHT_SUCCESS = 'SEARCHUSERRIGHT_SUCCESS';
export const SEARCHUSERRIGHT_FAILURE = 'SEARCHUSERRIGHT_FAILURE';

export const GETUSERSROLE_REQUEST = 'GETUSERSROLE_REQUEST';
export const GETUSERSROLE_SUCCESS = 'GETUSERSROLE_SUCCESS';
export const GETUSERSROLE_FAILURE = 'GETUSERSROLE_FAILURE';

export const GETUSERSRIGHT_REQUEST = 'GETUSERSRIGHT_REQUEST';
export const GETUSERSRIGHT_SUCCESS = 'GETUSERSRIGHT_SUCCESS';
export const GETUSERSRIGHT_FAILURE = 'GETUSERSRIGHT_FAILURE';

export const GETUSERROLETORIGHT_REQUEST = 'GETUSERROLETORIGHT_REQUEST';
export const GETUSERROLETORIGHT_SUCCESS = 'GETUSERROLETORIGHT_SUCCESS';
export const GETUSERROLETORIGHT_FAILURE = 'GETUSERROLETORIGHT_FAILURE';

export const UPDATEUSERROLETORIGHT_REQUEST = 'UPDATEUSERROLETORIGHT_REQUEST';
export const UPDATEUSERROLETORIGHT_SUCCESS = 'UPDATEUSERROLETORIGHT_SUCCESS';
export const UPDATEUSERROLETORIGHT_FAILURE = 'UPDATEUSERROLETORIGHT_FAILURE';

export const CREATEAPP_REQUEST = 'CREATEAPP_REQUEST';
export const CREATEAPP_SUCCESS = 'CREATEAPP_SUCCESS';
export const CREATEAPP_FAILURE = 'CREATEAPP_FAILURE';

export const APPDATABYID_REQUEST = 'APPDATABYID_REQUEST';
export const APPDATABYID_SUCCESS = 'APPDATABYID_SUCCESS';
export const APPDATABYID_FAILURE = 'APPDATABYID_FAILURE';

export const UPDATEAPP_REQUEST = 'UPDATEAPP_REQUEST';
export const UPDATEAPP_SUCCESS = 'UPDATEAPP_SUCCESS';
export const UPDATEAPP_FAILURE = 'UPDATEAPP_FAILURE';

export const DELETEAPP_SUCCESS = 'DELETEAPP_SUCCESS';
export const DELETEAPP_REQUEST = 'DELETEAPP_REQUEST';
export const DELETEAPP_FAILURE = 'DELETEAPP_FAILURE';

export const SEARCHAPP_SUCCESS = 'SEARCHAPP_SUCCESS';
export const SEARCHAPP_REQUEST = 'SEARCHAPP_REQUEST';
export const SEARCHAPP_FAILURE = 'SEARCHAPP_FAILURE';

export const SEARCHUSERROLEID_SUCCESS = 'SEARCHUSERROLEID_SUCCESS';
export const SEARCHUSERROLEID_REQUEST = 'SEARCHUSERROLEID_REQUEST';
export const SEARCHUSERROLEID_FAILURE = 'SEARCHUSERROLEID_FAILURE';

export const GETAPPBYPUBLISHERID_SUCCESS = 'GETAPPBYPUBLISHERID_SUCCESS';
export const GETAPPBYPUBLISHERID_REQUEST = 'GETAPPBYPUBLISHERID_REQUEST';
export const GETAPPBYPUBLISHERID_FAILURE = 'GETAPPBYPUBLISHERID_FAILURE';

export const INSERTAPPMONETIZATION_SUCCESS = 'INSERTAPPMONETIZATION_SUCCESS';
export const INSERTAPPMONETIZATION_REQUEST = 'INSERTAPPMONETIZATION_REQUEST';
export const INSERTAPPMONETIZATION_FAILURE = 'INSERTAPPMONETIZATION_FAILURE';

export const GETAPPMONETIZATION_SUCCESS = 'GETAPPMONETIZATION_SUCCESS';
export const GETAPPMONETIZATION_REQUEST = 'GETAPPMONETIZATION_REQUEST';
export const GETAPPMONETIZATION_FAILURE = 'GETAPPMONETIZATION_FAILURE';

export const UPDATEAPPMONETIZATION_SUCCESS = 'UPDATEAPPMONETIZATION_SUCCESS';
export const UPDATEAPPMONETIZATION_REQUEST = 'UPDATEAPPMONETIZATION_REQUEST';
export const UPDATEAPPMONETIZATION_FAILURE = 'UPDATEAPPMONETIZATION_FAILURE';

export const REMOVEAPPMONETIZATION_SUCCESS = 'REMOVEAPPMONETIZATION_SUCCESS';
export const REMOVEAPPMONETIZATION_REQUEST = 'REMOVEAPPMONETIZATION_REQUEST';
export const REMOVEAPPMONETIZATION_FAILURE = 'REMOVEAPPMONETIZATION_FAILURE';

export const ACTIVEAPPMONETIZATION_SUCCESS = 'ACTIVEAPPMONETIZATION_SUCCESS';
export const ACTIVEAPPMONETIZATION_REQUEST = 'ACTIVEAPPMONETIZATION_REQUEST';
export const ACTIVEAPPMONETIZATION_FAILURE = 'ACTIVEAPPMONETIZATION_FAILURE';

export const INACTIVEAPPMONETIZATION_SUCCESS = 'INACTIVEAPPMONETIZATION_SUCCESS';
export const INACTIVEAPPMONETIZATION_REQUEST = 'INACTIVEAPPMONETIZATION_REQUEST';
export const INACTIVEAPPMONETIZATION_FAILURE = 'INACTIVEAPPMONETIZATION_FAILURE';

export const REMOVEUSERIMAGE_SUCCESS = 'REMOVEUSERIMAGE_SUCCESS';
export const REMOVEUSERIMAGE_REQUEST = 'REMOVEUSERIMAGE_REQUEST';
export const REMOVEUSERIMAGE_FAILURE = 'REMOVEUSERIMAGE_FAILURE';

export const UPDATEPROFILE = 'UPDATEPROFILE';

export const GETCUSTOMADS_SUCCESS = 'GETCUSTOMADS_SUCCESS';
export const GETCUSTOMADS_REQUEST = 'GETCUSTOMADS_REQUEST';
export const GETCUSTOMADS_FAILURE = 'GETCUSTOMADS_FAILURE';

export const INSERTCUSTOMADS_SUCCESS = 'INSERTCUSTOMADS_SUCCESS';
export const INSERTCUSTOMADS_REQUEST = 'INSERTCUSTOMADS_REQUEST';
export const INSERTCUSTOMADS_FAILURE = 'INSERTCUSTOMADS_FAILURE';

export const REMOVECUSTOMADS_SUCCESS = 'REMOVECUSTOMADS_SUCCESS';
export const REMOVECUSTOMADS_REQUEST = 'REMOVECUSTOMADS_REQUEST';
export const REMOVECUSTOMADS_FAILURE = 'REMOVECUSTOMADS_FAILURE';

export const SENDPUSHNOTIFICATION_SUCCESS = 'SENDPUSHNOTIFICATION_SUCCESS';
export const SENDPUSHNOTIFICATION_REQUEST = 'SENDPUSHNOTIFICATION_REQUEST';
export const SENDPUSHNOTIFICATION_FAILURE = 'SENDPUSHNOTIFICATION_FAILURE';

export const NOTIFICATIONCOUNT_SUCCESS = 'NOTIFICATIONCOUNT_SUCCESS';
export const NOTIFICATIONCOUNT_REQUEST = 'NOTIFICATIONCOUNT_REQUEST';
export const NOTIFICATIONCOUNT_FAILURE = 'NOTIFICATIONCOUNT_FAILURE';

export const NOTIFICATIONPG_SUCCESS = 'NOTIFICATIONPG_SUCCESS';
export const NOTIFICATIONPG_REQUEST = 'NOTIFICATIONPG_REQUEST';
export const NOTIFICATIONPG_FAILURE = 'NOTIFICATIONPG_FAILURE';

export const REMOVENOTIFICATION_SUCCESS = 'REMOVENOTIFICATION_SUCCESS';
export const REMOVENOTIFICATION_REQUEST = 'REMOVENOTIFICATION_REQUEST';
export const REMOVENOTIFICATION_FAILURE = 'REMOVENOTIFICATION_FAILURE';

export const VIEWNOTIFICATION_SUCCESS = 'VIEWNOTIFICATION_SUCCESS';
export const VIEWNOTIFICATION_REQUEST = 'VIEWNOTIFICATION_REQUEST';
export const VIEWNOTIFICATION_FAILURE = 'VIEWNOTIFICATION_FAILURE';

export const GETUSERSCOUNTS_SUCCESS = 'GETUSERSCOUNTS_SUCCESS';
export const GETUSERSCOUNTS_REQUEST = 'GETUSERSCOUNTS_REQUEST';
export const GETUSERSCOUNTS_FAILURE = 'GETUSERSCOUNTS_FAILURE';

export const GETUSERSPG_SUCCESS = 'GETUSERSPG_SUCCESS';
export const GETUSERSPG_REQUEST = 'GETUSERSPG_REQUEST';
export const GETUSERSPG_FAILURE = 'GETUSERSPG_FAILURE';

export const SEARCHUSERS_SUCCESS = 'SEARCHUSERS_SUCCESS';
export const SEARCHUSERS_REQUEST = 'SEARCHUSERS_REQUEST';
export const SEARCHUSERS_FAILURE = 'SEARCHUSERS_FAILURE';

export const INACTIVEUSER_SUCCESS = 'INACTIVEUSER_SUCCESS';
export const INACTIVEUSER_REQUEST = 'INACTIVEUSER_REQUEST';
export const INACTIVEUSER_FAILURE = 'INACTIVEUSER_FAILURE';

export const CHANGE_NAME = 'CHANGE_NAME';
export const GETUSERRIGHTS = 'GETUSERRIGHTS';
export const SETUSERRIGHTS = 'SETUSERRIGHTS';

