// export const REGISTER_USERROLE_REQUEST = 'REGISTER_USERROLE_REQUEST';
// export const REGISTER_USERROLE_SUCCESS = 'REGISTER_USERROLE_SUCCESS';
// export const REGISTER_USERROLE_FAILURE = 'REGISTER_USERROLE_FAILURE';

// export const COUNT_USERROLE_REQUEST = 'COUNT_USERROLE_REQUEST';
// export const COUNT_USERROLE_SUCCESS = 'COUNT_USERROLE_SUCCESS';
// export const COUNT_USERROLE_FAILURE = 'COUNT_USERROLE_FAILURE';
