const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Social Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/widgets': 'Widgets',
  '/profile': 'Profile',
  '/change-password': 'ChangePassword',
  '/userrole': 'UserRole',
  '/userright': 'UserRight',
  '/userroletoright': 'UserRoleToRight',
  '/createapp': 'CreateApp',
  '/listapp': 'ListApp',
  '/editapp': 'EditApp',
  '/viewapp/:id': 'ViewApp',
  '/application': 'Profile',
  '/advertiser' : 'Advertiser',
  '/publisher' : 'Publisher',
  '/custom-ads' : 'CustomAds',
  '/monetization-network' : 'MonetizationNetwork',
  '/notifications' : 'Notifications',
  '/list-notifications' : 'ListNotifications',
  '/view-notification/:id' : 'ViewNotifications'
};
export default routes;
